################################################################
# File Generated by Codelink Debugger
#   Tue Feb 13 02:28:25 2018
#
# NOTE: Execute this macro after the debugger has been launched.
################################################################


## Breakpoints for riscv_core

codelink debugger -cpu_label riscv_core set breakpoint -symbol {puts} -continue -silent -always {sim_printf riscv_core}

codelink debugger -cpu_label riscv_core set breakpoint -symbol {main} -always

codelink debugger -cpu_label riscv_core set breakpoint -symbol {printf} -continue -silent -always {sim_printf riscv_core}


## Printpoints for riscv_core


## Watchpoints for riscv_core

